version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
      - unzip -q terraform.zip && mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - echo "Running terraform destroy..."
      - cd terraform
      - echo "bucket = \"${TF_STATE_BUCKET}\"" > backend.tfvars
      - terraform init -backend-config=backend.tfvars
      - terraform destroy -auto-approve
